jdk: openjdk8

before_install:
- "./install-protoc.sh" 

script:
- chmod +x build.sh
- "./build.sh"

env:
  global:
  - BINTRAY_USERNAME=cloudstatebot
  # API key encrypted with: travis encrypt --pro -r cloudstateio/springboot-support BINTRAY_PASSWORD={password}
  - secure: "aYxwzNgvlh8hLpRUDu+p8RfhmjUCA3HoJ3iJgcaDoBdttsIS7vQbWIOALhbauoYjQvmNfbW3p9vpog/YlxEnEQQSN+UvA7QttAPFE24TCiqOAxD1JTBQ5k8L6ZmOJBhsl8l/zIejQ4XVLO8GfEhXrFziBxAzmnIumQmvuonAz6qmhvk/q2aWHzLuYml0vvHkRCL2n5Rf75S5/Wsnpgm9BcVoGj6d0+HyQY5T3GOHHykgExXQdXRkrdfG1IDWYmlXGif+TL/tZN7RMJLHBstFaPalQfvu25RoNGcTK3j+daYUDoSu00CMugd6AutlmSFKqTfDLUR5mPeKbh0x9s75tSjCjsgBwrD/uB405FYvYNZcJhXpvARENCBXGoPMxFbe237/doB6LZAN0kTmcoY1zx13aymcooAinq7hj0fBW6pP7O7AKGbY/AsQUw6BAgo7vbBPoXKi6d3KaEUjbFqNi8Z14Gocdy+xUG70vW/ot8oaryGmAgjooIjHQVf7vwxYSPnFJg9iHZMwF09HAxlmx83zLhLEMscrhbBIX0ZbEkYYc5OEit4mz/OTPnly9M8REarb4xvYxC+tRN1l4Zt0OnBvAnB8l05aIOX8QJ9mWv/2XgG5dycbDagApcWCYAOR9B84FywvhPvkXEFVE9n7RWfaeGWgtZYBdphTIfvf81g="

deploy:
  provider: script
  script: deployment/deploy-release.sh
  skip_cleanup: true
  on:
    tags: true
    repo: cloudstateio/springboot-support
